import { Option } from '~/types/settings';

export const supportedLanguages: Option[] = [
  {
    code: 'af',
    fullCode: 'af_ZA',
    name: 'Afrikaans',
    nameRu: 'Африканский',
    nativeName: 'Afrikaans',
  },
  { code: 'sq', fullCode: 'sq_AL', name: 'Albanian', nameRu: 'Албанский', nativeName: 'Shqip' },
  {
    code: 'ar',
    fullCode: 'ar_SA',
    name: 'Arabic',
    nameRu: 'Арабский',
    nativeName: 'اللغة العربية',
  },
  { code: 'hy', fullCode: 'hy_AM', name: 'Armenian', nameRu: 'Армянский', nativeName: 'Հայերեն' },
  {
    code: 'az',
    fullCode: 'az_AZ',
    name: 'Azerbaijani',
    nameRu: 'Азербайджанский',
    nativeName: 'azərbaycan dili',
  },
  { code: 'eu', fullCode: 'eu_ES', name: 'Basque', nameRu: 'Баскский', nativeName: 'euskara' },
  {
    code: 'be',
    fullCode: 'be_BY',
    name: 'Belarusian',
    nameRu: 'Белорусский',
    nativeName: 'беларуская мова',
  },
  { code: 'bn', fullCode: 'bn_BD', name: 'Bengali', nameRu: 'Бенгальский', nativeName: 'বাংলা' },
  {
    code: 'bs',
    fullCode: 'bs_BA',
    name: 'Bosnian',
    nameRu: 'Боснийский',
    nativeName: 'bosanski jezik',
  },
  {
    code: 'bg',
    fullCode: 'bg_BG',
    name: 'Bulgarian',
    nameRu: 'Болгарский',
    nativeName: 'български език',
  },
  // { code: 'my', fullCode: 'my_MM', name: 'Burmese', nameRu: 'Бирманский', nativeName: 'ဗမာစာ' },
  { code: 'ca', fullCode: 'ca_ES', name: 'Catalan', nameRu: 'Каталанский', nativeName: 'Català' },
  {
    code: 'zh-Hans',
    fullCode: 'zh-Hans_CN',
    name: 'Chinese Simplified',
    nameRu: 'Китайский упрощенный ',
    nativeName: '中文',
  },
  {
    code: 'zh-Hant',
    fullCode: 'zh-Hant_TW',
    name: 'Chinese Traditional',
    nameRu: 'Китайский традиционный ',
    nativeName: '中文',
  },
  { code: 'cs', fullCode: 'cs_CZ', name: 'Czech', nameRu: 'Чешский', nativeName: 'čeština' },
  { code: 'da', fullCode: 'da_DK', name: 'Danish', nameRu: 'Датский', nativeName: 'dansk' },
  {
    code: 'nl',
    fullCode: 'nl_NL',
    name: 'Dutch',
    nameRu: 'Нидерландский',
    nativeName: 'Nederlands',
  },
  { code: 'en', fullCode: 'en_US', name: 'English', nameRu: 'Английский', nativeName: 'English' },
  { code: 'et', fullCode: 'et_EE', name: 'Estonian', nameRu: 'Эстонский', nativeName: 'eesti' },
  { code: 'fi', fullCode: 'fi_FI', name: 'Finnish', nameRu: 'Финский', nativeName: 'suomi' },
  { code: 'fr', fullCode: 'fr_CA', name: 'French', nameRu: 'Французский', nativeName: 'Français' },
  { code: 'gl', fullCode: 'gl_ES', name: 'Galician', nameRu: 'Галисийский', nativeName: 'galego' },
  { code: 'ka', fullCode: 'ka_GE', name: 'Georgian', nameRu: 'Грузинский', nativeName: 'ქართული' },
  { code: 'de', fullCode: 'de_DE', name: 'German', nameRu: 'Немецкий', nativeName: 'Deutsch' },
  { code: 'el', fullCode: 'el_GR', name: 'Greek', nameRu: 'Греческий', nativeName: 'Ελληνικά' },
  { code: 'gu', fullCode: 'gu_IN', name: 'Gujarati', nameRu: 'Гуджарати', nativeName: 'ગુજરાતી' },
  { code: 'ha', fullCode: 'ha_NE', name: 'Hausa', nameRu: 'Хауса', nativeName: 'هَوُسَ' },
  { code: 'hi', fullCode: 'hi_IN', name: 'Hindi', nameRu: 'Хинди', nativeName: 'हिन्दी' },
  { code: 'hu', fullCode: 'hu_HU', name: 'Hungarian', nameRu: 'Венгерский', nativeName: 'magyar' },
  {
    code: 'is',
    fullCode: 'is_IS',
    name: 'Icelandic',
    nameRu: 'Исландский',
    nativeName: 'Íslenska',
  },
  {
    code: 'id',
    fullCode: 'id_ID',
    name: 'Indonesian',
    nameRu: 'Индонезийский',
    nativeName: 'Bahasa Indonesia',
  },
  { code: 'ga', fullCode: 'ga_IE', name: 'Irish', nameRu: 'Ирландский', nativeName: 'Gaeilge' },
  { code: 'it', fullCode: 'it_IT', name: 'Italian', nameRu: 'Итальянский', nativeName: 'Italiano' },
  { code: 'ja', fullCode: 'ja_JP', name: 'Japanese', nameRu: 'Японский', nativeName: '日本語' },
  { code: 'kn', fullCode: 'kn_IN', name: 'Kannada', nameRu: 'Дравидийский', nativeName: 'ಕನ್ನಡ' },
  { code: 'kk', fullCode: 'kk_KZ', name: 'Kazakh', nameRu: 'Казахский', nativeName: 'қазақ тілі' },
  { code: 'km', fullCode: 'km_KH', name: 'Khmer', nameRu: 'Кхмерский', nativeName: 'ខេមរភាសា' },
  // { code: 'rw', fullCode: 'rw_RW', name: 'Kinyarwanda', nameRu: 'Киньяруанда', nativeName: 'Ikinyarwanda' },
  { code: 'ko', fullCode: 'ko_KR', name: 'Korean', nameRu: 'Корейский', nativeName: '한국어' },
  { code: 'ku', fullCode: 'ku_IR', name: 'Kurdish', nameRu: 'Курдский', nativeName: 'Kurdî' },
  { code: 'ky', fullCode: 'ky_KG', name: 'Kyrgyz', nameRu: 'Киргизский', nativeName: 'Кыргызча' },
  { code: 'lo', fullCode: 'lo_LA', name: 'Lao', nameRu: 'Лаосский', nativeName: 'ພາສາ' },
  {
    code: 'lv',
    fullCode: 'lv_LV',
    name: 'Latvian',
    nameRu: 'Латышский',
    nativeName: 'latviešu valoda',
  },
  {
    code: 'lt',
    fullCode: 'lt_LT',
    name: 'Lithuanian',
    nameRu: 'Литовский',
    nativeName: 'lietuvių kalba',
  },
  {
    code: 'lb',
    fullCode: 'lb_LU',
    name: 'Luxembourgish',
    nameRu: 'Люксембургский',
    nativeName: 'Lëtzebuergesch',
  },
  {
    code: 'mk',
    fullCode: 'mk_MK',
    name: 'Macedonian',
    nameRu: 'Македонский',
    nativeName: 'македонски јазик',
  },
  {
    code: 'mg',
    fullCode: 'mg_MG',
    name: 'Malagasy',
    nameRu: 'Малагасийский',
    nativeName: 'fiteny malagasy',
  },
  {
    code: 'ms',
    fullCode: 'ms_MY',
    name: 'Malay',
    nameRu: 'Малайский',
    nativeName: 'Bahasa Malaysia',
  },
  { code: 'ml', fullCode: 'ml_IN', name: 'Malayalam', nameRu: 'Малаялам', nativeName: 'മലയാളം' },
  { code: 'mt', fullCode: 'mt_MT', name: 'Maltese', nameRu: 'Мальтийский', nativeName: 'Malti' },
  { code: 'mi', fullCode: 'mi_NZ', name: 'Māori', nameRu: 'Маори', nativeName: 'te reo Māori' },
  { code: 'mr', fullCode: 'mr_IN', name: 'Marathi', nameRu: 'Маратхи', nativeName: 'मराठी' },
  {
    code: 'mn',
    fullCode: 'mn_MN',
    name: 'Mongolian',
    nameRu: 'Монгольский',
    nativeName: 'Монгол хэл',
  },
  { code: 'ne', fullCode: 'ne_NP', name: 'Nepali', nameRu: 'Непальский', nativeName: 'नेपाली' },
  { code: 'no', fullCode: 'no_NO', name: 'Norwegian', nameRu: 'Норвежский', nativeName: 'Norsk' },
  { code: 'ps', fullCode: 'ps_AF', name: 'Pashto', nameRu: 'Пашто', nativeName: 'پښتو' },
  { code: 'fa', fullCode: 'fa_IR', name: 'Persian', nameRu: 'Персидский', nativeName: 'فارسی' },
  { code: 'pl', fullCode: 'pl_PL', name: 'Polish', nameRu: 'Польский', nativeName: 'język polski' },
  {
    code: 'pt',
    fullCode: 'pt_PT',
    name: 'Portuguese',
    nameRu: 'Португальский',
    nativeName: 'Português',
  },
  { code: 'ro', fullCode: 'ro_RO', name: 'Romanian', nameRu: 'Румынский', nativeName: 'Română' },
  { code: 'ru', fullCode: 'ru_RU', name: 'Russian', nameRu: 'Русский', nativeName: 'Русский' },
  {
    code: 'sm',
    fullCode: 'sm_WS',
    name: 'Samoan',
    nameRu: 'Самоанский',
    nativeName: "gagana fa'a Samoa",
  },
  {
    code: 'gd',
    fullCode: 'gd_GB',
    name: 'Scottish Gaelic',
    nameRu: 'Шотландский',
    nativeName: 'Gàidhlig',
  },
  {
    code: 'sr',
    fullCode: 'sr-Cyrl_RS',
    name: 'Serbian',
    nameRu: 'Сербский',
    nativeName: 'српски језик',
  },
  { code: 'sn', fullCode: 'sn_ZW', name: 'Shona', nameRu: 'Шона', nativeName: 'chiShona' },
  { code: 'sd', fullCode: 'sd_PK', name: 'Sindhi', nameRu: 'Синдхи', nativeName: 'सिन्धी' },
  { code: 'si', fullCode: 'si_LK', name: 'Sinhala', nameRu: 'Сингальский', nativeName: 'සිංහල' },
  { code: 'sk', fullCode: 'sk_SK', name: 'Slovak', nameRu: 'Словацкий', nativeName: 'slovenčina' },
  {
    code: 'sl',
    fullCode: 'sl_SI',
    name: 'Slovene',
    nameRu: 'Словенский',
    nativeName: 'slovenski jezik',
  },
  {
    code: 'so',
    fullCode: 'so_SO',
    name: 'Somali',
    nameRu: 'Сомалийский',
    nativeName: 'Soomaaliga',
  },
  { code: 'es', fullCode: 'es_ES', name: 'Spanish', nameRu: 'Испанский', nativeName: 'Español' },
  {
    code: 'su',
    fullCode: 'su_ID',
    name: 'Sundanese',
    nameRu: 'Суданский',
    nativeName: 'Basa Sunda',
  },
  { code: 'sw', fullCode: 'sw_TZ', name: 'Swahili', nameRu: 'Суахили', nativeName: 'Kiswahili' },
  { code: 'sv', fullCode: 'sv_SE', name: 'Swedish', nameRu: 'Шведский', nativeName: 'Svenska' },
  {
    code: 'tl',
    fullCode: 'tl_PH',
    name: 'Tagalog',
    nameRu: 'Тагальский',
    nativeName: 'Wikang Tagalog',
  },
  { code: 'tg', fullCode: 'tg_TJ', name: 'Tajik', nameRu: 'Таджикский', nativeName: 'тоҷикӣ' },
  { code: 'ta', fullCode: 'ta_IN', name: 'Tamil', nameRu: 'Тамильский', nativeName: 'தமிழ்' },
  { code: 'te', fullCode: 'te_IN', name: 'Telugu', nameRu: 'Телугу', nativeName: 'తెలుగు' },
  { code: 'th', fullCode: 'th_TH', name: 'Thai', nameRu: 'Тайский', nativeName: 'ไทย' },
  { code: 'tr', fullCode: 'tr_TR', name: 'Turkish', nameRu: 'Турецкий', nativeName: 'Türkçe' },
  { code: 'tk', fullCode: 'tk_TK', name: 'Turkmen', nameRu: 'Туркменский', nativeName: 'Türkmen' },
  {
    code: 'uk',
    fullCode: 'uk_UA',
    name: 'Ukrainian',
    nameRu: 'Украинский',
    nativeName: 'Українська',
  },
  { code: 'ur', fullCode: 'ur_PK', name: 'Urdu', nameRu: 'Урду', nativeName: 'اردو' },
  { code: 'uz', fullCode: 'uz_UZ', name: 'Uzbek', nameRu: 'Узбекский', nativeName: 'Ўзбек' },
  {
    code: 'vi',
    fullCode: 'vi_VN',
    name: 'Vietnamese',
    nameRu: 'Вьетнамский',
    nativeName: 'Tiếng Việt',
  },
  { code: 'cy', fullCode: 'cy_GB', name: 'Welsh', nameRu: 'Валлийский', nativeName: 'Cymraeg' },
  {
    code: 'fy',
    fullCode: 'fy_NL',
    name: 'Western Frisian',
    nameRu: 'Западно-фризский',
    nativeName: 'Frysk',
  },
  { code: 'xh', fullCode: 'xh_ZA', name: 'Xhosa', nameRu: 'Коса', nativeName: 'isiXhosa' },
  { code: 'yi', fullCode: 'yi_IL', name: 'Yiddish', nameRu: 'Идиш', nativeName: 'ייִדיש' },
  { code: 'zu', fullCode: 'zu_ZA', name: 'Zulu', nameRu: 'Зулусский', nativeName: 'isiZulu' },
  // { code: 'zh-CN', name: 'Chinese', nameRu: 'Китайский ', nativeName: '中文'}
];

export const interfaceLanguages: Option[] = [
  {
    code: 'zh',
    fullCode: 'Zh',
    name: 'Chinese',
    nameRu: 'Китайский упрощенный ',
    nativeName: '中文',
  },
  { code: 'en', fullCode: 'En', name: 'English', nameRu: 'Английский', nativeName: 'English' },
  { code: 'de', fullCode: 'De', name: 'German', nameRu: 'Немецкий', nativeName: 'Deutsch' },
  { code: 'ru', fullCode: 'Ru', name: 'Russian', nameRu: 'Русский', nativeName: 'Русский' },
  { code: 'es', fullCode: 'Es', name: 'Spanish', nameRu: 'Испанский', nativeName: 'Español' },
];
