export const categories = [
  { category: 'All', priority: 0, name: { All: 'All' } },
  // { category: 'shorts_video', priority: 14, name: { shorts_video: '🔥 Shorts' } },
  { category: 'music', priority: 2, name: { music: '🎼 Music' } },
  { category: 'food', priority: 10, name: { food: '🍔 Food' } },
  { category: 'tv-series', priority: 1, name: { 'tv-series': '🎬 Series' } },
  { category: 'games', priority: 4, name: { games: '🎮 Games' } },
  {
    category: 'films',
    priority: 3,
    name: { films: '🎥 Movies' },
  },
  { category: 'popular science', priority: 8, name: { 'popular science': '🔎 Popular science' } },
  { category: 'sport', priority: 11, name: { sport: '⚽️ Sport' } },
  { category: 'learn english', priority: 12, name: { 'learn english': '🎓 English' } },
  { category: 'Cars', priority: 13, name: { Cars: '🚘 Cars' } },
  { category: 'travelling', priority: 6, name: { travelling: '🏜 Traveling' } },
  { category: 'technology', priority: 7, name: { technology: '📡 Technologies' } },
  { category: 'TED', priority: 5, name: { TED: '🔴 TED' } },
  { category: 'animation', priority: 9, name: { animation: '🐣 Cartoons' } },
];
